### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by ghost** [alesguzik/cinema#1]
I've been looking for a similar solution i was wondering if development has been abandoned? Thanks :)

**Comment by alesya-h** [comment]
Last time I used it (half a year ago), it worked quite fine. At that moment Tract were transitioning to API 2.0, and this project used 1.0, which were supported. Looks like it's time to switch to new API.

**Comment by alesya-h** [comment]
Updated to work with trakt 2.0 and yify 2.0 APIs

**Comment by ghost** [comment]
Woah thanks! @alesguzik
